name: 'CI'

on:
  pull_request:
    branches: ['master']
  push:
    branches: ['master']

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: write
  packages: write
  checks: write
  pull-requests: write

jobs:
  build-test:
    name: "Build & Test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Publish dry run
        run: pnpm publish --dry-run
